
[rewrite_local]

# 纯广告接口和首页营销弹窗
^https:\/\/maicai\.api\.ddxq\.mobi\/(?:advert\/(?:startUpScreen|getAd|getPreloadAd|getAtmosphere)|homeApi\/getHomeAdPop)(?:\?|$) url script-response-body https://raw.githubusercontent.com/Zz1xuan/ONE/refs/heads/main/Rewrite/AdBlock/DingDong/ddxq_ad.js

[mitm]
hostname = maicai.api.ddxq.mobi, farm.api.ddxq.mobi
