let jsonData = $response.body;
try {
    let parsedData = JSON.parse(jsonData);
    delete parsedData.data.banners;
    delete parsedData.data.space;
    delete parsedData.data.entrance_cpoint;
    delete parsedData.data.creditMall;
    delete parsedData.data.entrance_xpoint;
    delete parsedData.data.single;
    delete parsedData.data.vipCenter;
    delete parsedData.data.button;
    delete parsedData.data.items;
    delete parsedData.data.purchase;
    delete parsedData.data.camera;
    delete parsedData.data.vipBanner;
    delete parsedData.data.name;
    delete parsedData.data.pktopicl;
    delete parsedData.data.taskCenter;
    delete parsedData.data.activity;
    delete parsedData.data.entrance_gpaper;
    delete parsedData.data.englishWord;
    delete parsedData.data.vipEnd;
    delete parsedData.data.moduleType;
    delete parsedData.data.header;
    delete parsedData.data.moduleType;
    delete parsedData.data.quickEntry;
    delete parsedData.data.exercise;
    delete parsedData.data.modules;
    delete parsedData.data.custom;
    delete parsedData.data.tutor2;
    delete parsedData.data.dialog;
    delete parsedData.data.path;
    delete parsedData.data.dailyNews;
    delete parsedData.data.cetrance_list;
    delete parsedData.data.tips;
    delete parsedData.data.entrance_cpaper;
    delete parsedData.data.entrance_xpaper;
    delete parsedData.data.entrance_gpoint;
    delete parsedData.data.moduleType;
    delete parsedData.data.cycleBanner;
    delete parsedData.data.entrance_free;
    delete parsedData.data.goldcoin;
    delete parsedData.data.aggregateTriple;
    delete parsedData.data.dialog;
    jsonData = JSON.stringify(parsedData);
} catch (error) {
    console.log("Error:", error);
}
$done({body: jsonData});
