#!name=声荐小助手
#!desc=小红花领取 + 每日抽奖自动化（无需看广告）
#!author=Zz1xuan
#!icon=https://raw.githubusercontent.com/Zz1xuan/ONE/main/icon/shengjian.png
#!homepage=https://github.com/Zz1xuan/ONE

[Script]
shengjian-cookie = type=http-response, pattern=^https:\/\/xcx\.myinyun\.com:4438\/napi\/, script-path=https://raw.githubusercontent.com/Zz1xuan/ONE/main/Script/task/shengjian-helper.js, requires-body=false, timeout=10
shengjian-task = type=cron, pattern=0 8,18 * * *, script-path=https://raw.githubusercontent.com/Zz1xuan/ONE/main/Script/task/shengjian-helper.js, timeout=60

[MITM]
hostname = xcx.myinyun.com
