[rewrite_local]
# 1. Splash ads
^https:\/\/api\.mcd\.cn\/bff\/portal\/home\/splash(?:\?.*)?$ url jsonjq-response-body .data.list=[]

# 2. Popup / floating campaign dialog
^https:\/\/api\.mcd\.cn\/bff\/portal\/richpop\/v2(?:\?.*)?$ url jsonjq-response-body .data.pop=null

# 3. Home top ad slots
^https:\/\/api\.mcd\.cn\/bff\/portal\/home\/index\/user(?:\?.*)?$ url jsonjq-response-body .data.topAds=[]
^https:\/\/api\.mcd\.cn\/bff\/portal\/home\/index(?:\?.*)?$ url jsonjq-response-body .data.topAds=[]

[mitm]
hostname = api.mcd.cn