# 一佬

# Reddit 去广告 + 关 NSFW
^https?:\/\/gql(-fed)?\.reddit\.com url script-response-body https://raw.githubusercontent.com/Zz1xuan/ONE/main/Script/AD/reddit.js

# Reddit 自动翻译
^https:\/\/gql(-fed)?\.reddit\.com\/ url script-request-header https://raw.githubusercontent.com/Zz1xuan/ONE/main/Script/AD/reddit.js

hostname = gql.reddit.com, gql-fed.reddit.com
