# 一佬

# Reddit 去广告 + 关 NSFW
^https?:\/\/gql(-fed)?\.reddit\.com url jsonjq 'walk(
  if type == "object" then
    (if .isNsfw == true then .isNsfw = false else . end)
    | (if .isNsfwMediaBlocked == true then .isNsfwMediaBlocked = false else . end)
    | (if .isNsfwContentShown == false then .isNsfwContentShown = true else . end)
    | (if (.commentsPageAds | type == "array") then (.commentsPageAds = []) else . end)
    | (if ((.node | type == "object") and (.node.cells | type == "array") and (.node.cells | any(.__typename? == "AdMetadataCell" or .isAdPost? == true))) then empty else . end)
    | (if (.node | type == "object") and (.node.adPayload | type == "object") then empty else . end)
    | (if .__typename == "AdPost" then empty else . end)
  else .
  end
)'

# Reddit 自动翻译
^https:\/\/gql(-fed)?\.reddit\.com\/ url script-request-header https://raw.githubusercontent.com/Zz1xuan/ONE/main/Script/AD/reddit.js

hostname = gql.reddit.com, gql-fed.reddit.com
